# -*- coding: utf-8 -*-
"""Regula falsi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SQVSvD6reN8XkHuS6lT5yVzBT_4NYLfb
"""

def regula_falsi(func, a, b, tol=1e-6, max_iter=100):
    if func(a) * func(b) >= 0:
        print("Regula Falsi method tidak dapat digunakan pada interval ini.")
        return None

    for i in range(max_iter):
        c = (a * func(b) - b * func(a)) / (func(b) - func(a))

        if abs(func(c)) < tol:
            return c

        if func(c) * func(a) < 0:
            b = c
        else:
            a = c

    print("Iterasi maksimum tercapai. Hasil yang diperoleh mungkin tidak konvergen.")
    return None

# Contoh penggunaan:
def f(x):
    return (x**2) - (6*x) + 5  # Misalnya, x^2 - 4 = 0

a = 3.0  # Nilai awal interval a
b = 6.0  # Nilai awal interval b
result = regula_falsi(f, a, b)
if result is not None:
    print(f"Hasil Regula Falsi: {result:.6f}")